### ISSUE TITLE
Feature checklist

### ISSUE THREAD

**Issue by deathcap** [voxel/voxel-clientmc#23]
* [x] Connect to server (via wsmc)
* [x] Display chunks
 * [x] Block change updates
* [x] Digging blocks
 * [ ] Mining start/stop (vs one-click)
 * [x] Server block break animation
* [x] Placing blocks
* [x] Inventory updates
* [x] Chat
* [ ] Entities
